dbt_demo:
  outputs:
    dev:
      dbname: test
      host: 10.90.65.61
      pass: LJ2008*
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
